### ISSUE TITLE
Adding cakerphp validation

### ISSUE THREAD

**Issue by phyron** [odan/slim4-tutorial#26]
Hi!
I'm following your amazing tutorial, thanks!

Now I try to use a cakephp validation, following your other tutorial.
https://odan.github.io/2020/10/18/slim4-cakephp-validation.html

But I don't know how to add ValidationExceptionMiddleware in middleware stack. 
I add this line on config/middleware.php file but the 500 error say me that's wrong way :)

```
     ...
    // Catch exceptions and errors
    $app->add(ErrorMiddleware::class);
    $app->add(ValidationExceptionMiddleware::class);

```

I try the same with respect/validation, with the same problem, I don't know how/where to add the middleware line.

**Comment by odan** [comment]
Hi @phyron Error 500 is just a general server error. Have you tried to enable the error details? Please check your error log files or maybe try to install Xdebug. My guess is that there is an autoloading issue because of a missing namespace. First try to get more error details, then we can see how to solve this issue.
