### ISSUE TITLE
How do you decide if function should be autoloaded

### ISSUE THREAD

**Issue by samuelgfeller** [odan/slim4-tutorial#28]
I saw that you recently added a `hydrate` function to the `slim4-skeleton` project and that got me wondering, how do you decide if a function is worth autoloading or not? And what implications does autoloading a function have, is it overhead?  

In the [PHP-Template](https://odan.github.io/2020/12/09/slim4-php-view.html) blogpost you recommended autoloading the `html()` function which escapes values and that made a lot of sense to me as it's:
1. A small function
2. Used frequently 
3. Difficult to include otherwise (DI not possible / not best practice)

I added another function that is used in templates (filter server side validation array for error message on a specific field). 

I pictured this autoloading thing as something that should only be needed in extreme necessity to be kept as light as possible but seeing you autoloading a hydrate function that could easily be injected in the constructor where it's needed, somewhat nuances my preconception.

Would you add other small helper functions that are used frequently or was `hydrate` an exception?

**Comment by odan** [comment]
Hi Samuel!

In terms of overhead, this little feature is not a "big deal" for PHP. But I know what you mean. The thing is that custom functions in PHP are more and more "discouraged" for application specific code, because they are not OOP and cannot be autloaded like classes. Like everywhere, there are exceptions like `html()` and `__()` and other very small helpers.

I agree with you that this `hydrate` function should be better moved into a class.

**Comment by samuelgfeller** [comment]
Alright, makes sense to me. 

And thanks for the classy hydrate function without library! It came exactly at the right time when I was about to need it. 

Again and again, you save me from spending countless useless hours on a specific thing (and I take time to understand it and sometimes adapt to my needs, don't worry I don't just copy and paste)
