### ISSUE TITLE
A Single Action Controller should use only one Service.

### ISSUE THREAD

**Issue by MarcDeckert** [odan/slim4-tutorial#35]
Hey Daniel, i just bought your book last week and i really like it! 👍

My question cam along with this extract from the book: 
„A Single Action Controller should use only one Service and one Responder.“

Is this quote also valid when developing websites not APIs?

My homepage should display a simplified list of products in one section as well as google reviews in an other section. From my point of view i‘ll need at least two service classes. E.g ProductShortListReader and CustomerReviewReader.

Best regards Marc. ☺️

**Comment by odan** [comment]
Hi @MarcDeckert 

Thanks for buying my eBook. :-)

> Is this quote also valid when developing websites not APIs?

Yes, it doesn't matter if it's a website or an API.

> My homepage should display a simplified list of products in one section as well as google reviews in an other section. From my point of view i‘ll need at least two service classes. E.g ProductShortListReader and CustomerReviewReader.

It depends on the bound context. The question here is for which other use cases ProductShortListReader and CustomerReviewReader are used at all. Preferably for only one specific use case.

Without knowing the exact details, it is hard to answer this in general.

I would guess that you already use ProductShortListReader and CustomerReviewReader for another API endpoint, right?
If yes, then I would **not** reuse these application services in another application service, because of the breaking bounded context.

In general, I would try to split all these different **use cases** into specific, services. So for each endpoint (URL, route) there should be only one use case specific service class. If you have a piece of common logic, split this logic into a separate class and share it with the other classes.

**Comment by MarcDeckert** [comment]
@odan  Thanks for your quick reply! 

> I would guess that you already use ProductShortListReader and CustomerReviewReader for another API endpoint, right?

While ProductShortListReader currently has its use case in two different routes/actions the CustomerReviewReader is only used in my entry /home route. (Btw. maybe "Finder" would be a better suffix for both Services than of "Reader") 

> In general, I would try to split all these different use cases into specific, services. So for each endpoint (URL, route) there should be only one use case specific service class. 

But how do I name it? HomepageService and CampingplatzService seem to be a little bit vacuous, right? 

> If you have a piece of common logic, split this logic into a separate class and share it with the other classes.

All right so ProductShortListReader could be shared. But what about CustomerReviewReader? It's only used in my /home route. Would you recommend to put its logic directly in the HomepageService?

**Comment by odan** [comment]
> While ProductShortListReader currently has its use case in two different routes/actions the CustomerReviewReader is only used in my entry /home route. (Btw. maybe "Finder" would be a better suffix for both Services than of "Reader")

I use the prefix "Reader" for GET endpoints that reads a very specific set of data, e.g. by ID. I use the "Finder" prefix for endpoints that can find a collection of data, or not.

> But how do I name it? HomepageService and CampingplatzService seem to be a little bit vacuous, right?

Take a look at the context and find out what this specific class does (SRP), then it should be clear how to name it. Don't add the "Service" prefix, because it would be the same like calling a class "Manager" or so. Ask, what is this class responsible for. When the class is responsible for only one task, then it should be clear how to name it. When a class has to many responsibilities, then the class does too much and should be refactored.

> All right so ProductShortListReader could be shared. But what about CustomerReviewReader? It's only used in my /home route. Would you recommend to put its logic directly in the HomepageService?

I guess you may only need some very specific part of it, but not the whole logic to be shared. Try to find this shared logic and extract it into another class, but keep the ProductShortListReader and CustomerReviewReader for the API specific endpoint.
