### ISSUE TITLE
Multiple Database Connection using CakeDatabase

### ISSUE THREAD

**Issue by davidmtz-95** [odan/slim4-tutorial#39]
I'm trying to understeand how to implement this https://odan.github.io/2020/04/05/slim4-multiple-pdo-database-connections.html in my proyect, but i'm not really sure how i need to do it using the Cake Database Driver, could you give me a tip?

**Comment by davidmtz-95** [comment]
Context: I'm using your [Slim-Skeleton](https://github.com/slimphp/Slim-Skeleton) and for now i have the login in my "master database" once up the user loged in, i set the parameters of the tenant connection into a jwt, and i'm planing to check in a middleware and set the parameters connection of the user in session. What do you thing about it? And how can i implemented using the cake connection? Any comments help me a lot. Thank you.

**Comment by odan** [comment]
If you need multiple Cake database connection objects, it is very similar to what is shown in the PDO example.

Instead of extending from PDO, you extend it from the `Cake\Database\Connection;` class.

```php
<?php

namespace App\Database;

use Cake\Database\Connection;

class Connection2 extends Connection
{
    // must be empty
}
```

The add the DI container definition for Connection2:

```php
use App\Database\Connection2;
// ...

return [
    //...
    Connection2::class => function (ContainerInterface $container) {
        return new Connection2($container->get('settings')['db2']);
    },
];
```

If you have a "dynamic" connection that depends on the logged in user, then you could use a middleware that fetches the user from the request and builds the connection and set it into the DI container.

```php
// Middleware
use App\Database\Connection2;

// fetch user from request, jwt, session etc.
// ...

// your custom logic for the database connection parameters
// ...

// Connect the second connection to the database
$connection = new Connection2($connectionSettings);

// Set the new dynamic connection instance into the container
$this->container->set(Connection2::class, $connection);
```

Then use dependency injection as before.

**Comment by davidmtz-95** [comment]
Thanks for your early response, it was easier to implement than I thought. Regards
