### ISSUE TITLE
Are Unit tests really worth writing and maintaining on integration tested code?

### ISSUE THREAD

**Issue by samuelgfeller** [odan/slim4-tutorial#45]
I test extensively with integration tests. All sorts of exceptions and possibilities. Writing a Unit test on a well integration tested function feels quite useless and is sometimes a pain to implement properly (I’m thinking for e.g. about the function to test retrieving posts with different kinds of filters / invalid, not logged in etc. that I already tested with integration tests) and then to maintain as the function under test changes. 
Everything around this test function has to be mocked and taken care of, meaning that if the logic changes, I have to re-mock the right function return values. 
 
I think I find it actually better in a real world scenario to intensionally NOT write a lot of unit tests. Situations are actually quite rare where I think that Unit tests are a worthy addition to the integration tests. I don't really see myself maintaining detailed unit tests after doing so with integration tests that cover all cases. 

The question now is _when_ are they useful, and how do I determine if it's worth it to write and then maintain? Or is it OK to drop them completely if integration tested and only unit test a few select cases where I think it makes sense?

**Comment by odan** [comment]
I think you can't say this OR that. At the end of the day you need both, integration tests and unit tests.

For example, if you are implementing a library / package, then you will usually write more unit tests and less integration tests. However, if you are implementing a web application, the number of integration tests is usually much higher than the number of unit tests. However, the point here is not the exact number or "ratio" of the two types of tests, but rather what makes sense in terms of meaningfulness, time and money.

When you implement an integration tests for an API endpoint, you can cover everything from the action (controller), Domain (business logic) and the data access logic with just some lines of test code. Then you can change the complete implementation behind it and the test should still work. I think this is how tests should work, right?

So for me, it would make no sense to write extra unit-tests for each service or repository class, because this is too hard to maintain. Refactoring will become very stressful, because you have to refactor the unit-tests as well. So your unit tests are not a good indicator if the application works like before the refactoring. And this is not why we write tests, a test should be green before and after the refactoring. Then you know that writing tests makes actually sense and is worth the extra effort.

**Comment by samuelgfeller** [comment]
> For example, if you are implementing a library / package, then you will usually write more unit tests and less integration tests.

Okay yes, that makes sense.  

> Then you can change the complete implementation behind it and the test should still work. I think this is how tests should work, right?

This is so good to read. Yes, I very much think that the majority of tests should work like that, and it's the way I want to implement them.

> a test should be green before and after the refactoring

Never thought of it like this, but it makes sense. Thank you for your answer.
