### ISSUE TITLE
Re: Slim 4 tutorial with multi-table CRUD

### ISSUE THREAD

**Issue by sivakrith** [odan/slim4-tutorial#49]
Hello,
I followed https://odan.github.io/2019/11/05/slim4-tutorial.html page and could successfully create a base skeleton that works [ Insert, Read done, will do Delete and Update ].

About me.
New to PHP,  No knowledge of OOP.  Could not understand many concepts mentioned in the tutorial (like Closures, Dependency Injection etc.).   But got good experience in developing client/server applications in Powerbuilder.    With that knowledge, I could successfully follow your article and create one working skeleton.  Will improve that skeleton to my requirement in the coming days.

Now I need to learn how to
1.  Insert / Update / Delete / Read data from multiple tables.  eg.  Sales.  It will affect 2 tables minimum.  One table contains Customer Details, and the other table contains Item details, with one to many relationship.   Do you have any tutorial that teaches this ?
Fields of Table 1 :   Primarykey, Invoice No,, Invoice Date, Customer Name, Customer Address, Due Date, Transport Details etc.
Fields of Table 2 :   PrimaryKey, ForeignKey, ItemName, Quantity, Rate, Discount, Amount

2.  Would like to know whether this ebook (https://ko-fi.com/s/5f182b4b22) contains good tutorial to teach me what I didn't learned so far?

Happiness Always
BKR Sivaprakash

**Comment by odan** [comment]
Hi @sivakrith 

Thanks for your nice feedback.

If you want to find out more, you can study this repository with more examples:

* https://github.com/odan/slim4-skeleton

Note that this is just a very CRUD(ish) example to show the basics. In real life, the API endpoints should implement real **uses cases** and not only simple table operations over HTTP.

On my blog, I provide a lot of information:

* https://odan.github.io/2017/04/17/rest-restful-api-quick-reference.html
* https://odan.github.io/2019/12/03/slim4-cakephp-query-builder.html
* https://odan.github.io/2021/09/12/slim-cycle-query-builder.html
* https://odan.github.io/2019/12/01/slim4-laminas-db-query-builder-setup.html
* https://odan.github.io/2019/12/05/slim4-doctrine-dbal.html

Due to many support questions, some blog articles are no longer available for free, as I do not have the time to answer all questions in my spare time. 

In addition, the eBook contains over 32 **exclusive** chapters with web development topics on over 400 pages.
