### ISSUE TITLE
Re:  Validations and Error Handling (Particularly Method Not found Error)

### ISSUE THREAD

**Issue by sivakrith** [odan/slim4-tutorial#52]
Hello Odan,
With my slim knowledge in PHP/Slim, I'm really happy to learn to develop API using Slim framework with this tutorial.   
Now would like to extend further with validations and error handling modules.  I could see error handling chapter in your e-book but not Validation chapter there.   Is that (validation of input data) included in e-book?  If not, do you have any idea to comeup with one?  Won't it be better if there is some tutorial (chapter in e-book) to capture 'Method Not Found Error' ?
We do find it hard to name the API's with nouns alone, without verbs, when things grow up.   Not sure how you feel...

Happiness Always
BKR Sivaprakash

**Comment by odan** [comment]
Hi! The eBook contains two chapters about validation. If you have already bought it, I can send you a link to the latest online version.

According to "Method Not Found Error". Do you mean "405 Method Not Allowed"? If yes, there is an extra article about HTTP error handling in the eBook as well. It does not cover the specific error code 405, but the concept can be extended / adapted for all HTTP exceptions.
If you "invent" new HTTP method verbs, then you should think about it again, because some corporate firewalls do only allow the standard HTTP methods, and I'm sure that it's possible to use the standard HTTP verbs when you find a good URI path for your endpoints.
